### ISSUE TITLE
Increase radius?

### ISSUE THREAD

**Issue by cmunk** [tpanum/hjem#1]
For non-city real estate, then <1km is maybe a bit low --- maybe allow also <5km - 10km - 20km ? For rural areas :)

**Comment by tpanum** [comment]
Det er bestemt ikke usandt, men jeg har valgt at holde det til maks 1 kilometer af to primære årsager:
1. For befolkningstætte områder vil en øget radius skabe en meget stort mængde prisopslag, som vil belaste de eksterne services væsenligt mere.
2. Relevancen af "nærområdet" (som et sammenligningsgrundlag) bliver mindre som radius bliver større.

Overordnet er problemet at "landzoner" (som det kaldes i Danmark) bliver prissat eftervæsenligt andre vilkår end "byzoner", så vil ikke dette anbefale denne form for analyse til landzoner.

**Comment by cmunk** [comment]
Fair nok :)
